spring:
  datasource:
    url: ${SUPABASE_URL:jdbc:postgresql://db.gfxqaoqjpvmyxvkzmlej.supabase.co:5432/postgres}?prepareThreshold=0
    username: ${SUPABASE_DB_USERNAME:postgres}
    password: ${SUPABASE_DB_PASSWORD:ct&8Gz%25E2Xts.}
    driver-class-name: org.postgresql.Driver
    hikari:
      data-source-properties:
        prepareThreshold: 0
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    clean-disabled: false
    clean-on-validation-error: true
    url: ${SUPABASE_URL:jdbc:postgresql://db.gfxqaoqjpvmyxvkzmlej.supabase.co:5432/postgres}?prepareThreshold=0
    user: ${SUPABASE_DB_USERNAME:postgres}
    password: ${SUPABASE_DB_PASSWORD:ct&8Gz%25E2Xts.}
    baseline-on-migrate: true
    jdbc-properties:
      prepareThreshold: 0
  jackson:
    serialization:
      fail-on-empty-beans: false

jwt:
  secret: 8a3c9e7b2f4d6a1c8e5b9d3f2a7c4e1b8a3c9e7b2f4d6a1c8e5b9d3f2a7c4e1b
  expiration: 86400000 # 24 hours
