INSERT INTO vendors (created_at, updated_at, name, service_type, phone, email, address, is_active) VALUES
(current_timestamp, current_timestamp, 'Khandu Truss', 'Truss', '9561137899', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Irfan Truss', 'Truss', '9011010998', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Aquib (Skaff-folding)', 'Skaff-folding', '9730521614', NULL, 'Pune', true),

(current_timestamp, current_timestamp, 'Aravind', 'Sound & Lights', '8087313412', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Saif Ali', 'Sound & Lights', '7741970509', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Suren', 'Sound & Lights', '9987221155', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Rajendra', 'Sound', '9561958984', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Anish', 'Sound', '8623081192', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Amit', 'Sound', '9881236688', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'RS Satishe', 'Sound', '9850122274', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Khalid Dada', 'Sound & Lights', '9970786597', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Azar DS Sound & Lights', 'Sound & Lights', '9763997395', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Wajid Saikh', 'Sound & Lights', '9922460323', NULL, NULL, true),

(current_timestamp, current_timestamp, 'Anil', 'Lights', '7447770440', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Ramesh', 'Lights', '9975787063', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Vikaas', 'Lights', '7028619831', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Charan', 'Lights', '8805511174', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Sagar Mahebi', 'Lights & Genset', '7385371175', NULL, 'Mahabaleshwar', true),
(current_timestamp, current_timestamp, 'Dev', 'Lights', '9970739615', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Digamber Fairylight', 'Lights', '8888389561', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Rajjak', 'Lights', '9604704794', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Shripal (Nagar)', 'Lights', '9822522606', NULL, 'Nagar', true),
(current_timestamp, current_timestamp, 'Atul Neon Light', 'Lights', '8400100228', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Vinayak', 'Lights', '7709893547', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Moien', 'Lights', '9527519399', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Shakil Metal Light', 'Lights', '9860038622', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Gopal Lights Mumbai', 'Lights', '9821061339', NULL, 'Mumbai', true),
(current_timestamp, current_timestamp, 'Naushad Ali', 'Lights', '9929107896', NULL, 'Jaipur', true),
(current_timestamp, current_timestamp, 'Shankar Tripathi', 'Lights', '8766884989', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Trapathi', 'Lights', '9822188547', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Uday', 'Lights', '7909667933', NULL, NULL, true),

(current_timestamp, current_timestamp, 'Bajrang', 'Genset', '8888898050', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Genset Vendor', 'Genset', '7219035993', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Sawan Genset', 'Genset', '9673735160', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Manish Genset Connection', 'Genset', '9602428399', NULL, 'Udaipur', true),
(current_timestamp, current_timestamp, 'Mukesh Genset', 'Genset', '9829581480', NULL, 'Udaipur', true),
(current_timestamp, current_timestamp, 'Tayyab', 'Genset', '7073260574', NULL, 'Jaisalmer', true),

(current_timestamp, current_timestamp, 'Salman', 'Staging & Framing', '7030304837', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Sunil Prajapati', 'Staging & Framing', '7276780299', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Chetan Masmerise', 'Staging & Decor', '8087709293', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Zenil Joshi', 'Staging & Decor', '9930313337', NULL, 'Mumbai', true),

(current_timestamp, current_timestamp, 'Kashi Events', 'Decor', '9561501407', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Imran R Decorator', 'Decor', '9623666700', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'DK Wed Decor', 'Decor', '9890003599', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Deep Decor', 'Decor', '9637774493', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Sumit Shinde (launge Decor)', 'Decor', '8983309767', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Parth (Bella Decor)', 'Decor', '8828822674', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Shankar Tathe Mandap', 'Decor', '9011834555', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Dushant Tathe', 'Decor', '8975670703', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Girish Agrawal', 'Decor', '9921970197', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Babu Bhaiya Decorator', 'Decor', '9828603030', NULL, 'Jaisalmer', true),
(current_timestamp, current_timestamp, 'Bharat Pal Decor', 'Decor', '8769219633', NULL, 'Jaisalmer', true),
(current_timestamp, current_timestamp, 'Farhan Plug Point, Mirror', 'Decor', '8107896786', NULL, 'Udaipur', true),
(current_timestamp, current_timestamp, 'Harshit Mittal Decor', 'Decor', '9571613494', NULL, 'Jaipur', true),
(current_timestamp, current_timestamp, 'Jogishwari Real Flower Decor', 'Decor', '9604294875', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Pros Production', 'Decor', '9860691235', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Shakir Sir Real Flower Decor', 'Decor', '7378779288', NULL, 'Pune', true),

(current_timestamp, current_timestamp, 'Led wall', 'LED Wall', '8605370157', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Aniket', 'LED Wall', '7709202000', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Balu', 'LED Wall', '9764553767', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'LED Wall (Vendor)', 'LED Wall', '7992026219', NULL, 'Pune', true),

(current_timestamp, current_timestamp, 'Ershat', 'SFX', '9307879814', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Omkar', 'SFX', '9226068214', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Akshay', 'SFX', '7058747747', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Sfx', 'SFX', '9657652648', NULL, NULL, true),

(current_timestamp, current_timestamp, 'Sohail Balloon Decor', 'Balloon Decor', '9766021646', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Shahid Balloon Decor', 'Balloon Decor', '9527299769', NULL, 'Pune', true),

(current_timestamp, current_timestamp, 'Mohan Eicher', 'Transport', '9881323034', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Khullas Appa Eicher', 'Transport', '8308985417', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Ramesh Tempo', 'Transport', '9970329970', NULL, 'Pune', true),

(current_timestamp, current_timestamp, 'Chinmay Anchor', 'Anchor', '8329495144', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Vinod Anchor', 'Anchor', '9970171814', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Nilesh Anchor', 'Anchor', '9881453990', NULL, 'Pune', true),

(current_timestamp, current_timestamp, 'Milind DJ', 'DJ', '9823895234', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Vinsty DJ', 'DJ', '7744975799', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'DJ Pune', 'DJ', '8459062650', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Antriksh DJ', 'DJ', '9975581336', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Antriksh DJ 2', 'DJ', '9021333444', NULL, NULL, true),

(current_timestamp, current_timestamp, 'Riya Choreographer', 'Entertainment', '9356908109', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Hair Makeup Artist', 'Entertainment', '8805137966', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Saba Mehendi Artist', 'Entertainment', '8421717871', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Sneha Makeup Artist', 'Entertainment', '8446444593', NULL, 'Hingoli', true),
(current_timestamp, current_timestamp, 'Mayuri Makeup Artist', 'Entertainment', '7620347006', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Rakhi Makeup Artist', 'Entertainment', '8618189949', NULL, 'Bhusawal', true),
(current_timestamp, current_timestamp, 'Pooja Makeup Artist', 'Entertainment', '7276755225', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Atul Sonar Choreographer', 'Entertainment', '7972799254', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Rohit Choreographer', 'Entertainment', '9975674466', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Sandy Russian Supplier', 'Entertainment', '9373317054', NULL, 'Mumbai', true),
(current_timestamp, current_timestamp, 'Yashraj Entry Dancer', 'Entertainment', '8485853621', NULL, 'Pune', true),

(current_timestamp, current_timestamp, 'Vishwas 26 mm Storeis', 'Media', '9922702335', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Revati Photo/Vdo Grapher', 'Media', '9860814548', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Abhi Photo/Vdo Grapher', 'Media', '8485813084', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Nilesh Photo/Vdo Grapher', 'Media', '8483845541', NULL, 'Hingoli', true),
(current_timestamp, current_timestamp, 'Deep Reel Creater', 'Media', '9370150966', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Kunal Photographer', 'Media', '9730819417', NULL, 'Bhusawal', true),
(current_timestamp, current_timestamp, 'Prathamesh Photographer', 'Media', '9834923120', NULL, 'Bhusawal', true),
(current_timestamp, current_timestamp, 'Rushikesh Deshmukh Reel Creater', 'Media', '8263825059', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Pratyush Reel Creater', 'Media', '8696580650', NULL, 'Udaipur', true),
(current_timestamp, current_timestamp, 'Raj JB Wed Film Maker', 'Media', '9881659505', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Yogesh Patil Photographer', 'Media', '7972294014', NULL, NULL, true),

(current_timestamp, current_timestamp, 'Ravi kolours', 'Printing', '9762313810', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Pooja Graphics', 'Printing', '9850603236', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Kamlesh Printing', 'Printing', '9763666108', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Laxman Printing', 'Printing', '9022269547', NULL, 'Pune', true),

(current_timestamp, current_timestamp, 'Jirawala Laser 1', 'Laser Cutting', '7744888717', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Jirawala Laser 2', 'Laser Cutting', '7744888873', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Aastha MS Laser', 'Laser Cutting', '8698307772', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Manasi MS Laser', 'Laser Cutting', '7798991717', NULL, 'Pune', true),

(current_timestamp, current_timestamp, 'Govinda Labour Supplier', 'Labour Supplier', '9765395084', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Juned Labour Supplier', 'Labour Supplier', '8698183621', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Aashish Labour Supplier', 'Labour Supplier', '6393151239', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Sarfraj Labour Supplier', 'Labour Supplier', '6306526545', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Jatin Labour Supplier', 'Labour Supplier', '7062085352', NULL, 'Jodhpur', true),
(current_timestamp, current_timestamp, 'Mohit House Kipping', 'Labour Supplier', '7976896854', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Pruthvi Porter', 'Labour Supplier', '9307548061', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Sahitya House Kipping', 'Labour Supplier', '7985912908', NULL, NULL, true),

(current_timestamp, current_timestamp, 'Cane Basket', 'Making & Purchasing', '9902370318', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Resin Art Studio', 'Making & Purchasing', '8830650016', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Burani Acrylic 1', 'Making & Purchasing', '9850325616', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Burani Acrylic 2', 'Making & Purchasing', '9011958752', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Carpet Pisoli', 'Making & Purchasing', '7820963766', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Foam Flower Mumbai', 'Making & Purchasing', '9869613925', NULL, 'Mumbai', true),
(current_timestamp, current_timestamp, 'Five Star Decor', 'Making & Purchasing', '9373923033', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Piyush Deepchand', 'Making & Purchasing', '9823960100', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Luxe Basket', 'Making & Purchasing', '8744928086', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Manik Flower Hema', 'Making & Purchasing', '7086716889', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Kings Paper', 'Making & Purchasing', '9823267266', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'PN Art Desinger', 'Making & Purchasing', '8262829106', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Rakesh Shah Flower', 'Making & Purchasing', '9970087778', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Ravi Flower Market', 'Making & Purchasing', '9096089078', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Ravi Shende Paper Bag', 'Making & Purchasing', '9822434733', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'SN Art Acrylic Cutting', 'Making & Purchasing', '8698295515', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Wedding Props Banglore', 'Making & Purchasing', '9916457512', NULL, 'Banglore', true),
(current_timestamp, current_timestamp, 'Meet Bhalla Five Decor', 'Making & Purchasing', '9371053033', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Navketan Acrylic', 'Making & Purchasing', '9028010748', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Hariom Wps (Delhi)', 'Making & Purchasing', '7669666989', NULL, 'Delhi', true),
(current_timestamp, current_timestamp, 'Decor Cafe', 'Making & Purchasing', '9067593339', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Aarti Paper Bag', 'Making & Purchasing', '9823267333', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Abrar Neon Lights', 'Making & Purchasing', '8983840126', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Artificial Flowers', 'Making & Purchasing', '9371922043', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Manoj Colours (Paint)', 'Making & Purchasing', '8888806498', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Darshan Rangoli Pune', 'Making & Purchasing', '9850898982', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Dhananjay Acrylic Sheet', 'Making & Purchasing', '8793101277', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Gala Dryfruits', 'Making & Purchasing', '9422407176', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Shah Cloths', 'Making & Purchasing', '9822082265', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Julee Custom Bags', 'Making & Purchasing', '7498821933', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Mahaveer Sagar', 'Making & Purchasing', '9823307049', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Mahaveer Flowers', 'Making & Purchasing', '9822004541', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Pooja Artificial Flowers', 'Making & Purchasing', '9371044031', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Nayan Flower Market', 'Making & Purchasing', '9763090073', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Sanjay Gala', 'Making & Purchasing', '8446814959', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Santosh', 'Making & Purchasing', '7875116540', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Buquet (Near Wellness)', 'Making & Purchasing', '9732464485', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Rainbow Balloon Decor', 'Making & Purchasing', '9579569427', NULL, 'Pune', true),

(current_timestamp, current_timestamp, 'Ganesh Darode Mandap', 'Rental', '9422081172', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Party Prop Rental', 'Rental', '9860691235', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Walkie Sachin', 'Rental', '7350735807', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Kiran Patil Walkie', 'Rental', '8605553419', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Sagar Decorators', 'Rental', '7020897270', NULL, 'Pune', true),

(current_timestamp, current_timestamp, 'Chirag Bartander', 'Bartander', '9607792470', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Prakash Bartander', 'Bartander', '8806757547', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Praful Bartander', 'Bartander', '9834125414', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Shiv Bartander', 'Bartander', '9604522265', NULL, 'Pune', true),

(current_timestamp, current_timestamp, 'Mehboob Awati Games', 'Games & Activity', '9766831225', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Azim Dreamz Games', 'Games & Activity', '8888564439', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Adarsh Live Stall', 'Games & Activity', '7007755973', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Priyanka Live Stall', 'Games & Activity', '7219435976', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Pranali Live Stall', 'Games & Activity', '8275488009', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Deepak & Priya Live Singer', 'Games & Activity', '9756828449', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Gamimg Mania Mumbai', 'Games & Activity', '9834326076', NULL, 'Mumbai', true),
(current_timestamp, current_timestamp, 'Jayesh Live Bhajan', 'Games & Activity', '8668950480', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Naresh Jain Fluit', 'Games & Activity', '9822302996', NULL, NULL, true),
(current_timestamp, current_timestamp, 'Pradeep Gupta Natak', 'Games & Activity', '9967903658', NULL, 'Mumbai', true),
(current_timestamp, current_timestamp, 'Sandeep Jadhav Natak', 'Games & Activity', '8652854309', NULL, NULL, true),

(current_timestamp, current_timestamp, 'Appa Car', 'Logistics', '9096653082', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Ramesh Car', 'Logistics', '9980899420', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Anand Security Guard', 'Logistics', '9819399011', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Chunnu Food Packet', 'Logistics', '7767037645', NULL, 'Pune', true),

(current_timestamp, current_timestamp, 'Lucky Dhol', 'Barrat', '9975510671', NULL, 'Pune', true),
(current_timestamp, current_timestamp, 'Nana Band', 'Barrat', '8999324153', NULL, 'Mahabaleshwar', true),
(current_timestamp, current_timestamp, 'Jiten Panditji', 'Rituals', '8329520750', NULL, 'Pune', true);
