-- Add client_billable to expenses
ALTER TABLE expenses ADD COLUMN client_billable BOOLEAN DEFAULT FALSE;

-- Create petty cash transactions table
CREATE TABLE petty_cash_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_type VARCHAR(50) NOT NULL,
    amount NUMERIC(19, 2) NOT NULL,
    description TEXT NOT NULL,
    transaction_date DATE NOT NULL,
    recorded_by VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP WITHOUT TIME ZONE,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);
