ALTER TABLE bill_of_materials
ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT NOW(),
ADD COLUMN updated_at TIMESTAMP,
ADD COLUMN created_by VARCHAR(100),
ADD COLUMN updated_by VARCHAR(100);

ALTER TABLE raw_materials ALTER COLUMN current_stock TYPE DOUBLE PRECISION;
ALTER TABLE raw_materials ALTER COLUMN minimum_stock TYPE DOUBLE PRECISION;
ALTER TABLE bill_of_materials ALTER COLUMN quantity TYPE DOUBLE PRECISION;
ALTER TABLE stock_transactions ALTER COLUMN quantity TYPE DOUBLE PRECISION;