-- Add soft delete columns to CRM tables
ALTER TABLE leads ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE, ADD COLUMN deleted_at TIMESTAMP, ADD COLUMN deleted_by VARCHAR(100);
ALTER TABLE clients ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE, ADD COLUMN deleted_at TIMESTAMP, ADD COLUMN deleted_by VARCHAR(100);
ALTER TABLE follow_ups ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE, ADD COLUMN deleted_at TIMESTAMP, ADD COLUMN deleted_by VARCHAR(100);

-- Add soft delete columns to Events tables
ALTER TABLE events ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE, ADD COLUMN deleted_at TIMESTAMP, ADD COLUMN deleted_by VARCHAR(100);
ALTER TABLE tasks ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE, ADD COLUMN deleted_at TIMESTAMP, ADD COLUMN deleted_by VARCHAR(100);
ALTER TABLE vendors ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE, ADD COLUMN deleted_at TIMESTAMP, ADD COLUMN deleted_by VARCHAR(100);

-- Add soft delete columns to Inventory tables
ALTER TABLE products ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE, ADD COLUMN deleted_at TIMESTAMP, ADD COLUMN deleted_by VARCHAR(100);
ALTER TABLE raw_materials ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE, ADD COLUMN deleted_at TIMESTAMP, ADD COLUMN deleted_by VARCHAR(100);
ALTER TABLE stock_transactions ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE, ADD COLUMN deleted_at TIMESTAMP, ADD COLUMN deleted_by VARCHAR(100);

-- Add soft delete columns to Sales tables
ALTER TABLE quotations ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE, ADD COLUMN deleted_at TIMESTAMP, ADD COLUMN deleted_by VARCHAR(100);

-- Add soft delete columns to Finance tables
ALTER TABLE invoices ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE, ADD COLUMN deleted_at TIMESTAMP, ADD COLUMN deleted_by VARCHAR(100);
ALTER TABLE payments ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE, ADD COLUMN deleted_at TIMESTAMP, ADD COLUMN deleted_by VARCHAR(100);
ALTER TABLE expenses ADD COLUMN is_deleted BOOLEAN NOT NULL DEFAULT FALSE, ADD COLUMN deleted_at TIMESTAMP, ADD COLUMN deleted_by VARCHAR(100);
